---
# vars file for pve_vm_patching
#
# Variables for Proxmox API calls
pve_api_node:   #Hostname of the api receiver hypervisor
pve_domain:     #Your domain
pve_api_user:   #API user ID
pve_api_token:  #API user token ID
pve_api_secret: #API user token secret
pve_check_cert: #boolean - Check hypervisor SSL cert
