---
- name: Pull podman images
  become_user: "{{ podman_user }}"
  loop: "{{ podman_images_list }}"
  loop_control:
    label: "{{ item.name }}"
  containers.podman.podman_image:
    name: "{{ item.img }}"
    tag: "{{ item.tag }}"
    force: "{{ item.frc | default(omit) }}"

- name: Ensure no dangling images are left
  when: podman_images_prune|default('false')|bool
  become_user: "{{ podman_user }}"
  containers.podman.podman_prune:
    image: "{{ podman_images_prune }}"
