---
# vars file
#
# Proxmox API login informations
pve_api_user:
pve_api_token_id:
pve_api_token_secret:

# IP or FQDN of you pve host that will be receiving api calls 
pve_api_host:
email_host:
smtp_host:

# Cloud init info
cloud_init_username:
cloud_init_password:
cloud_init_sshkey:
deployment_nodes:
